name: Build and Push Docker Image for Roid Software

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ROID_TOKEN }}

      - name: Extract short commit SHA
        id: vars
        run: echo "SHA7=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}"
          TAG="${IMAGE_NAME}:${SHA7}"

          docker build -f docker/build_and_push.Dockerfile -t $TAG -t $IMAGE_NAME:latest .
          docker push $TAG
          docker push $IMAGE_NAME:latest

      - name: Output pushed image
        run: |
          echo "Pushed Image: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${SHA7}"
